### ISSUE TITLE
Buggy behaviour while interacting with furniture in certain situations 

### ISSUE THREAD

**Issue by Red-IO** [NotLe0n/BetterChests#12]
When hovering the cursor over storage furniture that's not loaded fully, it freezes the character in place and pauses actions like swinging a pickaxe until the cursor is moved away. Also neither the furniture nor the blocks it is on can be broken or used.

How to reproduce:
1. Run alongside Magic Builder https://steamcommunity.com/sharedfiles/filedetails/?id=3024322683
2.  Build a structure that creates dressers (e.g. large house)
3. optional: disable Magic Builder
4. hover over dresser while standing nearby

Testing showed that manually placed dressers work as intended and that problem persists while Better Chests is the only mod installed.

```
[02:45:32.655] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BetterChests.Edits.ChestHoverEdits.MouseOver(Int32 i, Int32 j, Int32 type) in BetterChests\src\Edits\ChestHoverEdits.cs:line 29
   at Terraria.ModLoader.TileLoader.MouseOver(Int32 i, Int32 j) in tModLoader\Terraria\ModLoader\TileLoader.cs:line 947
   at Terraria.Player.TileInteractionsMouseOver(Int32 myX, Int32 myY) in tModLoader\Terraria\Player.cs:line 28250
   at Terraria.Player.TileInteractionsCheck(Int32 myX, Int32 myY) in tModLoader\Terraria\Player.cs:line 25574
   at Terraria.Player.LookForTileInteractions() in tModLoader\Terraria\Player.cs:line 25477
   at Terraria.Player.Update(Int32 i) in tModLoader\Terraria\Player.cs:line 22472
   at Terraria.Main.DoUpdateInWorld(Stopwatch sw) in tModLoader\Terraria\Main.cs:line 14967
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 14603
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 14141
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 546
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 213
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 78
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in tModLoader\Terraria\MonoLaunch.cs:line 64
   at System.Threading.Thread.StartCallback()

```

**Comment by NotLe0n** [comment]
Fixed in v1.9.1 (9c773701390f431f5adc0972e5b82a5a0e071cf7)
